test: &default

  # Credentials for REST APIs
  client_id: AbzaH53fP_JqxgmnvxMqLMXQp4l3uvdRrRKzjiBGVtp6KqoeuUiQS-U33DQetV2OSBtWGffzZ5gIFokr
  client_secret: ENHgnf4ux_K2-kwDQ4GurW_pT5sbIqFjT6qa8eLXpeuARs27xZ39WvKj_7bXo_5KtPZo3obn7cH5v2rx

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: comprado@hola.com
  password: animex1980
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: comprado@hola.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
